wip

diff --git a/.github/workflows/build_worker.yml b/.github/workflows/build_worker.yml
--- a/.github/workflows/build_worker.yml
+++ b/.github/workflows/build_worker.yml
@@ -41,9 +41,9 @@ jobs:
       - name: Get options
         id: options
         env:
-          TAG: ${{ inputs.new_tag_short }}
-          NAME: ${{ inputs.name }}
-          SHA: ${{ inputs.sha_short }}
+          TAG: ${{ inputs.new_tag_short || '' }}
+          NAME: ${{ inputs.name || '' }}
+          SHA: ${{ inputs.sha_short || '' }}
         run: |
           if [[ -n $TAG ]]; then
             PLATFORMS=linux/amd64,linux/arm64
@@ -54,10 +54,13 @@ jobs:
               TAGS+=,${IMAGE_NAME}:${TAG%%.*}
               TAGS+=,${IMAGE_NAME}:latest
             fi
-          else
+          elif [[ -n $SHA ]]; then
             PLATFORMS=linux/amd64
             VERSION=$SHA
-            TAGS=$IMAGE_NAME:$NAME
+            TAGS=$IMAGE_NAME:$SHA
+          else
+            echo "ERROR: No tag or SHA provided." >&2
+            exit 1
           fi
           echo "platforms=$PLATFORMS" >> "$GITHUB_OUTPUT"
           echo "version=$VERSION" >> "$GITHUB_OUTPUT"
